# Generated by Django 5.2.8 on 2026-09-03 12:43

import uuid
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Transaction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=12)),
                ('event_details', models.TextField()),
                ('event_type', models.CharField(choices=[('CREDIT', 'Credit'), ('DEBIT', 'Debit')], max_length=6)),
                ('category', models.CharField(max_length=100)),
                ('is_returnable', models.BooleanField(default=False)),
                ('returnable_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12)),
                ('related_transactions', models.JSONField(blank=True, default=list)),
                ('transaction_at', models.DateTimeField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
